version: '3.6'
services:
  eva-client-service:
    image: ${SKYNET_APPLICATION_EVA_CLIENT_SERVICE:-drydock.workiva.net/workiva/eva-client-service:latest-release}
    ports:
      - 8080:8080
    environment:
      - CATALOG_URL=LOCAL
      - LOGBACK_APPENDER=STDOUT
      - IAM_UNSAFE=true
      - SANITIZE_EXCEPTIONS=false
      - TRACE_RECORDER=off
      - DISABLE_TELEMETRY=true
